apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v11
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v11
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v11
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v11
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v0.19.1
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
          command:
            - /heapster
            - --source=kubernetes:''
            - --sink=influxdb:http://monitoring-influxdb.kube-system.svc.cluster.local:8086
            - --stats_resolution=30s
            - --sink_frequency=1m
